name: PDE_Screening
channels:
  - conda-forge
  - pytorch
dependencies:
  - conda-forge::python=3.9
  - pytorch::pytorch=1.8.1
  - conda-forge::matplotlib=3.4.1
  - conda-forge::notebook=6.3.0
  - conda-forge::numpy=1.20.2
  - conda-forge::pandas=1.2.4
  - conda-forge::seaborn=0.11.1
  - conda-forge::tifffile=2021.2.0
  - conda-forge::scipy=1.6.3
  - conda-forge::pip
  - pip:
      - cellpose=0.6.4
      - watermark=2.2.0